POST localhost:8080/v1/api/auth/login
Content-Type: application/json

{
  "login": "root",
  "password": "root"
}

###

GET localhost:8080/v1/api/invoices
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5NjU0MTQ3LCJleHAiOjE4MDE1OTk2NTQxNDd9.vbJtAYd-EsC-3FepSo8kEZCE42ejqXTtToN9T8hv9p0

###

GET localhost:8080/v1/api/owners
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5NjU0MTQ3LCJleHAiOjE4MDE1OTk2NTQxNDd9.vbJtAYd-EsC-3FepSo8kEZCE42ejqXTtToN9T8hv9p0

###

GET localhost:8080/v1/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5NjU0MTQ3LCJleHAiOjE4MDE1OTk2NTQxNDd9.vbJtAYd-EsC-3FepSo8kEZCE42ejqXTtToN9T8hv9p0

###

POST localhost:8080/v1/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5NjU0MTQ3LCJleHAiOjE4MDE1OTk2NTQxNDd9.vbJtAYd-EsC-3FepSo8kEZCE42ejqXTtToN9T8hv9p0

{
  "login": "test 13loginddddd",
  "password": "test passworddddddddddddddddd",
  "name": "Ivan",
  "surname": "Ivanov",
  "patronymic": "Ivanovich",
  "birthday": "2020-01-01",
  "address": {
    "city": "Minsk"
  },
  "email": "test@mail.com",
  "roles": ["SYSADMIN"]
}

###


POST localhost:8080/v1/api/invoices
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5NjU0MTQ3LCJleHAiOjE4MDE1OTk2NTQxNDd9.vbJtAYd-EsC-3FepSo8kEZCE42ejqXTtToN9T8hv9p0

{
  "invoiceNumber": "TTN321332",
  "registrationDate": "2020-01-01",
  "shipper": "OOO 'Test company', Minsk, Nemiga 3 ",
  "consignee": "OOO 'Test warehouse', Smolensk, Lenina 5 ",
  "driverId": 1,
  "products": [
    {
      "name": "test product",
      "quantity": 5,
      "measure": "bochka",
      "price": 100,
      "sum": 500,
      "mass": "100 kg"
    }
  ]
}

###


GET localhost:8080/v1/api/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5NjU0MTQ3LCJleHAiOjE4MDE1OTk2NTQxNDd9.vbJtAYd-EsC-3FepSo8kEZCE42ejqXTtToN9T8hv9p0

###


