POST localhost:8080/v1/api/auth/login
Content-Type: application/json

{
  "login": "dispatcher",
  "password": "root"
}

###

// --- Owners ---

GET localhost:8080/v1/api/owners
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkaXNwYXRjaGVyIiwicm9sZXMiOlsiRElTUEFUQ0hFUiJdLCJpYXQiOjE2MDIwMzAzMTAsImV4cCI6MTYwMjg5NDMxMH0.p_H7VercLTjeP_rscHthUYWZlny--eCl3mbyS_DYNJw

###

// --- Users ---

GET localhost:8080/v1/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkaXNwYXRjaGVyIiwicm9sZXMiOlsiRElTUEFUQ0hFUiJdLCJpYXQiOjE2MDIwMzIxOTMsImV4cCI6MTYwMjg5NjE5M30.pLOVvHxMy9mXIBdP9LM081meLktIRrxSlDerHgReLiE

###

POST localhost:8080/v1/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkaXNwYXRjaGVyIiwicm9sZXMiOlsiRElTUEFUQ0hFUiJdLCJpYXQiOjE2MDE4NjM1NzIsImV4cCI6MTYwMjcyNzU3Mn0.ZgUF0XbqJh42rLLPiKge1zhCvh1GEE3fWqUzU15hpCQ

{
  "login": "admin3",
  "password": "root",
  "name": "Ivan",
  "surname": "Ivanov",
  "patronymic": "Ivanovich",
  "birthday": "2020-01-01",
  "address": {
    "country": "Belarus",
    "city": "Minsk",
    "street": "Nemiga",
    "house": "32",
    "flat": "13"
  },
  "email": "test3@mail.com",
  "phone": "31233",
  "roles": [
    "ADMIN"
  ]
}

###

PUT localhost:8080/v1/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNjAwNjkyNTg1LCJleHAiOjE2MDE1NTY1ODV9.IS6oFE36ybMUjmaB9VEo6RBu14LfhAnz2XFeHV1dNUw

{
  "id": 6,
  "login": "adm3321",
  "password": "root",
  "name": "Ivan",
  "surname": "Ivanov",
  "patronymic": "Ivanovich",
  "birthday": "2020-01-01",
  "address": {
    "country": "Belarus",
    "city": "Minsk",
    "street": "Nemiga",
    "house": "32",
    "flat": "13"
  },
  "email": "test7@mail.com",
  "roles": [
    "MANAGER"
  ]
}

###

// --- Invoices ---

GET localhost:8080/v1/api/invoices/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkaXNwYXRjaGVyIiwicm9sZXMiOlsiRElTUEFUQ0hFUiJdLCJpYXQiOjE2MDE4NTkxODIsImV4cCI6MTYwMjcyMzE4Mn0.RESk4vbtagVlsH3q6Iwu57teAyrw29nttDnSLrVAjto

###

GET localhost:8080/v1/api/invoices
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

###

POST localhost:8080/v1/api/invoices
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNjAwODgxNjgxLCJleHAiOjE2MDE3NDU2ODF9.oVWUaQZE031CJxLLf7S2sDBuH1g9M6WqPNryh524ahI

{
  "status": "REGISTERED",
  "invoiceNumber": "TTN8888888",
  "registrationDate": "2020-01-03",
  "productOwnerId": 1,
  "shipper": "OOO 'Test company', Minsk, Nemiga 3 ",
  "consignee": "OOO 'Test warehouse', Smolensk, Lenina 5 ",
  "driverId": 1,
  "products": [
    {
      "name": "test product",
      "quantity": 10,
      "quantityMeasure": "BARREL",
      "price": 56,
      "mass": "100",
      "massMeasure": "TON",
      "currency": "RUB"
    }
  ]
}

####

POST localhost:8080/v1/api/invoices/status
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

{
  "id": 1,
  "status": "ACCEPTED"
}

###

// --- Clients test ---

GET localhost:8080/v1/api/clients/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

###

POST localhost:8080/v1/api/clients
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

{
  "name": "Подвезём",
  "type": "SP",
  "payerAccountNumber": "123456787",
  "country": "Belarus",
  "city": "Minsk",
  "street": "street test",
  "house": "45",
  "flat": "1",
  "registrationDate": "2020-01-01",
  "email": "test2@mail.ru"
}

###

// --- Waybills ---

GET localhost:8080/v1/api/waybills/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

###

POST localhost:8080/v1/api/waybills
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

{
  "points": [
    {
      "place": "Orsha",
      "passed": false,
      "passageDate": "",
      "waybillId": "",
      "id": null
    }
  ],
  "invoiceId": 1,
  "autoId": 1,
  "departureDate": "2020-09-30",
  "arrivalDate": "2020-09-30"
}

###

GET localhost:8080/v1/api/drivers/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTYwMDk4MzYwMCwiZXhwIjoxNjAxODQ3NjAwfQ.a2spH9o7L4uYuatAjGb--VuYzZHbTKyUnfgzEeiefZE

###

POST localhost:8080/v1/api/invoices/status
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

{
  "id": 1,
  "status": "CLOSED",
  "comment": "Clean delivery"
}

###
// --- Points ---

POST localhost:8080/v1/api/waybills/points
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

{
  "id": 12
}

###

GET localhost:8080/v1/api/waybills/points/12
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

###
// --- Acts ---

GET localhost:8080/v1/api/acts/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

###

POST localhost:8080/v1/api/acts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

{
  "invoiceId": 1,
  "registrationDate": "2020-09-28",
  "consigneeWorker": "Sergey Sergeev",
  "products": [
    {
      "id": 4,
      "productStatus": "LOST",
      "comment": "all... all is gone",
      "lostQuantity": 5
    }
  ]
}

###
PUT localhost:8080/v1/api/users/photo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

{
  "photo": ""
}

###