POST localhost:8080/v1/api/auth/login
Content-Type: application/json

{
  "login": "root",
  "password": "root"
}

####
GET localhost:8080/v1/api/auth/id
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

###

// --- Owners ---

GET localhost:8080/v1/api/owners
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

###

// --- Users ---

GET localhost:8080/v1/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

###

POST localhost:8080/v1/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

{
  "login": "manager1",
  "password": "manager1",
  "name": "Ivan",
  "surname": "Ivanov",
  "patronymic": "Ivanovich",
  "birthday": "2020-01-01",
  "address": {
    "city": "Minsk"
  },
  "email": "test@mail.com",
  "roles": [
    "MANAGER"
  ]
}

###

// --- Invoices ---

GET localhost:8080/v1/api/invoices/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

###

GET localhost:8080/v1/api/invoices
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

###

POST localhost:8080/v1/api/invoices
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

{

  "status": "REGISTERED",
  "invoiceNumber": "TTN327788",
  "registrationDate": "2020-01-03",
  "shipper": "OOO 'Test company', Minsk, Nemiga 3 ",
  "consignee": "OOO 'Test warehouse', Smolensk, Lenina 5 ",
  "driverId": 1,
  "products": [
    {
      "name": "test product",
      "quantity": 10,
      "measure": "barrel",
      "price": 56,
      "sum": 13,
      "mass": "100 kg"
    }
  ]
}

####

POST localhost:8080/v1/api/invoices/status
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

{
"id": 1,
"status": "ACCEPTED",
  "checkingUserId": 1
}

###

// --- Clients test ---

GET localhost:8080/v1/api/clients/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

###

POST localhost:8080/v1/api/clients
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5Njk2MTU3LCJleHAiOjE2MDA1NjAxNTd9.XwG82XBIRywcBDqkTeH2e7SVNwmIIUOzUhRY4fAMroQ

{
  "name": "Подвезём",
  "type": "SP",
  "payerAccountNumber": "123456787",
  "country": "Belarus",
  "city": "Minsk",
  "street": "street test",
  "house": "45",
  "flat": "1",
  "registrationDate": "2020-01-01",
  "email": "test2@mail.ru"
}

###

###

// --- Waybills ---

GET localhost:8080/v1/api/waybills/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

###

POST localhost:8080/v1/api/waybills
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiU1lTQURNSU4iXSwiaWF0IjoxNTk5MTM3ODU1LCJleHAiOjE4MDE1OTkxMzc4NTV9.Pf5XEA7ure-0R67U-T5YShQIMXw6iYCJRDsVorZ96BI

{
  "departureDate": "2020-01-01",
  "arrivalDate": "2021-01-03",
  "autoId": 1,
  "invoiceId": 1,
  "points": [
    {
      "place": "Vitebsk",
      "isPassed": true,
      "passageDate": "2020-01-01"
    }
  ]
}

###

