POST localhost:8080/v1/api/auth/login
Content-Type: application/json

{
  "login": "testLogin",
  "password": "password"
}

###

GET localhost:8080/v1/api/users/test
Content-Type: application/json
Authorization:

###

POST localhost:8080/v1/api/users/authenticate
Content-Type: application/json

{
  "login": "testLogin",
  "password": "password"
}

###