POST localhost:8080/v1/api/auth/login
Content-Type: application/json

{
  "login": "rootd",
  "password": "root"
}

###

GET localhost:8080/v1/api/users/test
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290Iiwicm9sZXMiOlsiQURNSU4iXSwiaWF0IjoxNTk3OTMwOTM2LCJleHAiOjE1OTc5MzI3MzZ9.CJeOw7s625mqyhCU__RNkCtE7HJ6BnTZ8XRNl_-vX94

###

POST localhost:8080/v1/api/users/authenticate
Content-Type: application/json

{
  "login": "testLogin",
  "password": "password"
}

###