 export const ACTION_CHANGE_USER_AND_COMPANY = "ACTION_CHANGE_USER_AND_COMPANY";

 export const ACTION_CHANGE_USER = "ACTION_CHANGE_USER";

 export const ACTION_CHANGE_JWT_TOKEN = 'ACTION_CHANGE_JWT_TOKEN'
