export const NEW_INVOICE_MESSAGE_TYPE = "NEW_INVOICE";
export const NEW_WAYBILL_MESSAGE_TYPE = "NEW_WAYBILL";
export const INVOICE_STATUS_UPDATE_MESSAGE_TYPE = "INVOICE_STATUS_UPDATE";
export const INVOICE_UPDATE_MESSAGE_TYPE = "INVOICE_UPDATE";
export const POINT_PASS_MESSAGE_TYPE = "POINT_PASS";